---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - cert.pottmeier.de
  resources:
  - tlssecretwatchers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cert.pottmeier.de
  resources:
  - tlssecretwatchers/finalizers
  verbs:
  - update
- apiGroups:
  - cert.pottmeier.de
  resources:
  - tlssecretwatchers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cert.pottmeier.de/v1
  resources:
  - tlssecretwatchers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - v1
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - v1
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
